### ISSUE TITLE
fyi, this is already in os.UserConfigHome

### ISSUE THREAD

**Issue by rwxrob** [Chaitanyabsprip/dotfiles#1]
https://github.com/Chaitanyabsprip/dotfiles/blob/33ff03af60d56747239008ec45bc99ee165aaaa2/internal/core/oscfg/main.go#L11

**Comment by chaitanyabsprip** [comment]
Most tools I use don't respect `os.UserConfigHome`, so I have to make my own implementation. Also I don't use windows, so don't care about it.
